apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: pod-maria
  labels:
    app: wordpress
    role: database
spec:
  containers:
  - image: mariadb:10
    name: maria
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3306
    envFrom:
      - prefix: 'MARIADB_'
        configMapRef:
          name: cm-maria