apiVersion: v1
kind: Pod
metadata:
  name: pod-wp
  labels:
    app: wordpress
    role: website

spec:
  containers:
  - image: wordpress:5
    name: pod-wp
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    envFrom:
    - prefix: 'WORDPRESS_DB_'
      configMapRef:
        name: cm-wp