version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      #- /windows/www:/usr/share/nginx/html/:rw
      - /home/www/html:/usr/share/nginx/html/:rw
      - /home/www/nginx/conf/vhost/:/etc/nginx/conf.d/:ro
      #- /home/www/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/www/log/nginx/:/var/log/nginx/:rw
    #links:
    #  - php-fpm:fpm
    depends_on:
      - php-fpm
    networks:
      - lnmp
  php-fpm:
    image: swr.cn-north-1.myhuaweicloud.com/engine56/php:1.0.5
    expose:
      - "9000"
    volumes:
      #- /windows/www:/var/www/html/:rw
      - /home/www/html:/var/www/html/:rw
      - /home/www/php/conf/php.ini:/usr/local/etc/php/php.ini:ro
      - /home/www/php/conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - /home/www/log/php-fpm/:/var/log/php-fpm/:rw
    networks:
      - lnmp
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - /home/www/mysql/conf/my.cnf:/etc/mysql/my.cnf:ro
      - /home/www/mysql/data:/var/lib/mysql/:rw
      - /home/www/log/mysql/:/var/log/mysql/:rw
      - /home/www/mysql/mysql-files/:/var/lib/mysql-files:rw
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    #restart: always
    networks:
      - lnmp
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - lnmp
  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
    networks:
      - lnmp
networks:
  lnmp:
