version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - /windows/www:/usr/share/nginx/html/:rw
      - ./nginx:/etc/nginx/conf.d/:ro
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/log/nginx/:/var/log/nginx/:rw
    #privileged: true
    extra_hosts:
      - "say-words.qm.com:192.168.88.138"
      - "rec.qm.com:192.168.88.138"
      - "admin.qm.com:192.168.88.138"
      - "www.qm.com:192.168.88.138"
      - "home.mytest.com:192.168.88.138"
    depends_on:
      - php-fpm
    networks:
      - lnmp
  php-fpm:
    #image: swr.cn-north-1.myhuaweicloud.com/engine56/php:1.0.7
    image: myphp7.2:latest
    expose:
      - "9000"
    volumes:
      - /windows/www:/var/www/html/:rw
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - /var/log/php-fpm/:/var/log/php-fpm/:rw
    #privileged: true
    #env_file:
    #  - ./php-fpm.env
    extra_hosts:
      - "say-words.qm.com:192.168.88.138"
      - "rec.qm.com:192.168.88.138"
      - "admin.qm.com:192.168.88.138"
      - "www.qm.com:192.168.88.138"
      - "home.mytest.com:192.168.88.138"
    networks:
      - lnmp
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf:ro
      - /home/www/mysql/data:/var/lib/mysql/:rw
      - /var/log/mysql/:/var/log/mysql/:rw
      - /home/www/mysql/mysql-files/:/var/lib/mysql-files:rw
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    #restart: always
    networks:
      - lnmp
  redis:
    image: myredis:latest
    ports:
      - "6379:6379"
    volumes: 
      - ./redis/6379.conf:/usr/local/etc/redis/redis.conf:ro
      - /home/www/redis:/data/db:rw
    networks:
      - lnmp
#  mongodb:
#    image: mongo:3.7
#    ports:
#      - "27017:27017"
#    volumes:
#      - ./mongodb:/etc/mongo
#      - /home/www/mongodb:/data/db
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: 123456
#    networks:
#      - lnmp
#  nosql-client:
#    image: mongoclient/mongoclient:2.2.0
#    restart: always
#    ports: 
#      - 3000:3000
#    volumes:
#      - /home/www/nosql-client:/data/db
#    environment:
#      ROOT_URL: http://nosqlclient.mytest.com:3000/nosqlclient
#      MONGO_URL: mongodb://admin:123456@mongodb:27017
#      MONGOCLIENT_AUTH: "true"
#      MONGOCLIENT_USERNAME: admin
#      MONGOCLIENT_PASSWORD: 123456
#      #MONGOCLIENT_DEFAULT_CONNECTION_URL: mongodb:@mongodb:27017
#    depends_on:
#      - mongodb
#    networks:
#      - lnmp     
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8082:8082
#    environment:
#      ME_CONFIG_MONGODB_SERVER: mongodb
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
#    depends_on:
#      - mongodb
#    networks:
#      - lnmp
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8083:8080
#    networks:
#      - lnmp
networks:
  lnmp:
