version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - /data/htdocs/:/usr/share/nginx/html/:rw
      - /data/htdocs/docker-lnmp/nginx/conf.d/:/etc/nginx/conf.d/:ro
      #- /data/htdocs/docker-lnmp/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/log/nginx/:/var/log/nginx/:rw
    #privileged: true
    extra_hosts:
      - "say-words.qm.com:192.168.88.138"
      - "rec.qm.com:192.168.88.138"
      - "admin.qm.com:192.168.88.138"
      - "www.qm.com:192.168.88.138"
      - "home.mytest.com:192.168.88.138"
    depends_on:
      - php-fpm
#    networks:
#      - lnmp
  php-fpm:
    #image: swr.cn-north-1.myhuaweicloud.com/engine56/php:1.0.7
    image: myphp7.2:latest
    expose:
      - "9000"
    volumes:
      - /data/htdocs/:/var/www/html/:rw
      - /data/htdocs/docker-lnmp/php/php.ini:/usr/local/etc/php/php.ini:ro
      - /data/htdocs/docker-lnmp/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - /var/log/php-fpm/:/var/log/php-fpm/:rw
    #privileged: true
    #env_file:
    #  - ./php-fpm.env
    extra_hosts:
      - "say-words.qm.com:192.168.88.138"
      - "rec.qm.com:192.168.88.138"
      - "admin.qm.com:192.168.88.138"
      - "www.qm.com:192.168.88.138"
      - "home.mytest.com:192.168.88.138"
  mysql:
    image: mysql:5.6
    container_name: mysql5.6
    ports:
      - "3306:3306"
    volumes:
      - /data/htdocs/docker-lnmp/db/mysql/my.56.cnf:/etc/mysql/my.cnf:ro
      - /data/var/mysql5.6/data:/var/lib/mysql/:rw
      - /var/log/mysql5.6/:/var/log/mysql/:rw
      - /data/var/mysql5.6/mysql-files/:/var/lib/mysql-files:rw
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
  mysql-slave:
    image: mysql:5.6
    container_name: mysql5.6-slave
    ports:
      - "3307:3306"
    volumes:
      - /data/htdocs/docker-lnmp/db/mysql/my-slave.56.cnf:/etc/mysql/my.cnf:ro
      - /data/var/mysql5.6-slave/data:/var/lib/mysql/:rw
      - /var/log/mysql5.6-slave/:/var/log/mysql/:rw
      - /data/var/mysql5.6-slave/mysql-files/:/var/lib/mysql-files:rw
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    extra_hosts:
      - "master.mysql.me:192.168.29.143"

  rabbitmq37:
    image: rabbitmq:3.7.24-management
    container_name: rabbit3.7-m
    ports:
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
    volumes:
      - /data/var/rabbitmq37/:/var/lib/rabbitmq/
      - /data/htdocs/docker-lnmp/queue/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - /data/var/log/rabbitmq/:/var/log/rabbitmq/

  redis-master:
    image: redis:latest
    container_name: redis-master
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data/htdocs/queue/redis/:/etc/redis/
      - /data/var/redis-master:/data/db:rw
    command: redis-server /etc/redis/redis-master.conf
  redis-slave:
    image: redis:latest
    container_name: redis-slave
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - /data/htdocs/conf/redis/:/etc/redis/
      - /data/var/redis-slave:/data/db:rw
    command: redis-server /etc/redis/redis-slave.conf
    depends_on:
      - redis28
#  mongodb:
#    image: mongo:3.7
#    ports:
#      - "27017:27017"
#    volumes:
#      - ./mongodb:/etc/mongo
#      - /home/www/mongodb:/data/db
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: 123456
#    networks:
#      - lnmp
#  nosql-client:
#    image: mongoclient/mongoclient:2.2.0
#    restart: always
#    ports: 
#      - 3000:3000
#    volumes:
#      - /home/www/nosql-client:/data/db
#    environment:
#      ROOT_URL: http://nosqlclient.mytest.com:3000/nosqlclient
#      MONGO_URL: mongodb://admin:123456@mongodb:27017
#      MONGOCLIENT_AUTH: "true"
#      MONGOCLIENT_USERNAME: admin
#      MONGOCLIENT_PASSWORD: 123456
#      #MONGOCLIENT_DEFAULT_CONNECTION_URL: mongodb:@mongodb:27017
#    depends_on:
#      - mongodb
#    networks:
#      - lnmp     
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8082:8082
#    environment:
#      ME_CONFIG_MONGODB_SERVER: mongodb
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
#    depends_on:
#      - mongodb
#    networks:
#      - lnmp
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8083:8080
#    networks:
#      - lnmp
networks:
  default:
    external:
      name: lnmp
