version: "3"
services:
  sentinel:
    image: bladex/sentinel-dashboard:latest
    container_name: sentinel
    ports:
      - "8858:8858"
    restart: always
  seata-server:
    image: seataio/seata-server:1.4.0
    container_name: seata-server
    hostname: seata-server
    ports:
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
#      - STORE_MODE=db
      - SEATA_IP=192.168.29.129
    volumes:
      - /data/htdocs/docker-lnmp/java/seata-config/registry.conf:/seata-server/resources/registry.conf
networks:
  default:
    external:
      name: conf_default