version: '3'
services:
  es01:
    image: es7.1.1-with-ik-icu-pinyin:latest
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es_cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es7data01:/usr/share/elasticsearch/data
    extra_hosts:
      - "home.mytest.com:192.168.112.129"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  es02:
    image: es7.1.1-with-ik-icu-pinyin:latest
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es_cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es7data02:/usr/share/elasticsearch/data
    extra_hosts:
      - "home.mytest.com:192.168.112.129"
    networks:
      - esnet
  cerebro:
    image: lmenezes/cerebro:0.8.3
    container_name: cerebro
    ports:
      - "9100:9000"
    command:
      - -Dhosts.0.host=http://es01:9200
    depends_on:
      - es01
      - es02
#    restart: always
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    container_name: kibana7
    environment:
      I18N_LOCALE: "zh-CN"
      XPACK_GRAPH_ENABLED: "true"
      TIMELION_ENABLED: "true"
      XPACK_MONITORING_COLLECTION_ENABLED: "true"
      SERVER_HOST: "0.0.0.0"
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
#    volumes:
#      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - es01
      - es02
#    restart: always
    ports:
      - "5601:5601"
    networks:
      - esnet
volumes:
  es7data01:
    driver: local
  es7data02:
    driver: local

networks:
  esnet:
    driver: bridge
