integrations:
  agent:
    enabled: true
    relabel_configs:
      - action: replace
        source_labels:
          - agent_hostname
        target_label: instance
      - action: replace
        target_label: job
        replacement: "integrations/agent-check"
    metric_relabel_configs:
      - action: keep
        regex: (prometheus_target_.*|prometheus_sd_discovered_targets|agent_build.*|agent_wal_samples_appended_total|process_start_time_seconds)
        source_labels:
          - __name__
  # Add here any snippet that belongs to the `integrations` section.
  # For a correct indentation, paste snippets copied from Grafana Cloud at the beginning of the line.
#logs:
#  configs:
#    - clients:
#        - basic_auth:
#            password: <your_loki_pass>
#            username: <your_loki_user>
#          url: <your_loki_url>
#      name: integrations
#      positions:
#        filename: /tmp/positions.yaml
#      scrape_configs:
#      # Add here any snippet that belongs to the `logs.configs.scrape_configs` section.
#      # For a correct indentation, paste snippets copied from Grafana Cloud at the beginning of the line.
metrics:
  configs:
    - name: integrations
      remote_write:
        - url: http://prometheus:9090/api/v1/write
      scrape_configs:
        # Add here any snippet that belongs to the `metrics.configs.scrape_configs` section.
        # For a correct indentation, paste snippets copied from Grafana Cloud at the beginning of the line.
        - job_name: integrations-rabbitmq
          scrape_interval: 10s
          relabel_configs:
            - replacement: 'integrations-rabbitmq-instance'
              target_label: instance
          static_configs:
            - targets: [ 'rabbit3.8.9:15692' ]
          params:
            queue: [ 'example.ampq.canal' ]
  global:
    scrape_interval: 60s
  wal_directory: /tmp/grafana-agent-wal